/*
 * This file is generated by jOOQ.
 */
package co.db.jooq.tables.records;


import co.db.jooq.tables.Model;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModelRecord extends UpdatableRecordImpl<ModelRecord> implements Record8<Integer, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>model.model_id</code>.
     */
    public ModelRecord setModelId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>model.model_id</code>.
     */
    public Integer getModelId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>model.model_name</code>.
     */
    public ModelRecord setModelName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>model.model_name</code>.
     */
    public String getModelName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>model.model_instaURL</code>.
     */
    public ModelRecord setModelInstaurl(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>model.model_instaURL</code>.
     */
    public String getModelInstaurl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>model.model_gender</code>.
     */
    public ModelRecord setModelGender(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>model.model_gender</code>.
     */
    public String getModelGender() {
        return (String) get(3);
    }

    /**
     * Setter for <code>model.model_born</code>.
     */
    public ModelRecord setModelBorn(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>model.model_born</code>.
     */
    public String getModelBorn() {
        return (String) get(4);
    }

    /**
     * Setter for <code>model.model_nationality</code>.
     */
    public ModelRecord setModelNationality(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>model.model_nationality</code>.
     */
    public String getModelNationality() {
        return (String) get(5);
    }

    /**
     * Setter for <code>model.model_height</code>.
     */
    public ModelRecord setModelHeight(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>model.model_height</code>.
     */
    public String getModelHeight() {
        return (String) get(6);
    }

    /**
     * Setter for <code>model.model_figure</code>.
     */
    public ModelRecord setModelFigure(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>model.model_figure</code>.
     */
    public String getModelFigure() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, String, String, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, String, String, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Model.MODEL.MODEL_ID;
    }

    @Override
    public Field<String> field2() {
        return Model.MODEL.MODEL_NAME;
    }

    @Override
    public Field<String> field3() {
        return Model.MODEL.MODEL_INSTAURL;
    }

    @Override
    public Field<String> field4() {
        return Model.MODEL.MODEL_GENDER;
    }

    @Override
    public Field<String> field5() {
        return Model.MODEL.MODEL_BORN;
    }

    @Override
    public Field<String> field6() {
        return Model.MODEL.MODEL_NATIONALITY;
    }

    @Override
    public Field<String> field7() {
        return Model.MODEL.MODEL_HEIGHT;
    }

    @Override
    public Field<String> field8() {
        return Model.MODEL.MODEL_FIGURE;
    }

    @Override
    public Integer component1() {
        return getModelId();
    }

    @Override
    public String component2() {
        return getModelName();
    }

    @Override
    public String component3() {
        return getModelInstaurl();
    }

    @Override
    public String component4() {
        return getModelGender();
    }

    @Override
    public String component5() {
        return getModelBorn();
    }

    @Override
    public String component6() {
        return getModelNationality();
    }

    @Override
    public String component7() {
        return getModelHeight();
    }

    @Override
    public String component8() {
        return getModelFigure();
    }

    @Override
    public Integer value1() {
        return getModelId();
    }

    @Override
    public String value2() {
        return getModelName();
    }

    @Override
    public String value3() {
        return getModelInstaurl();
    }

    @Override
    public String value4() {
        return getModelGender();
    }

    @Override
    public String value5() {
        return getModelBorn();
    }

    @Override
    public String value6() {
        return getModelNationality();
    }

    @Override
    public String value7() {
        return getModelHeight();
    }

    @Override
    public String value8() {
        return getModelFigure();
    }

    @Override
    public ModelRecord value1(Integer value) {
        setModelId(value);
        return this;
    }

    @Override
    public ModelRecord value2(String value) {
        setModelName(value);
        return this;
    }

    @Override
    public ModelRecord value3(String value) {
        setModelInstaurl(value);
        return this;
    }

    @Override
    public ModelRecord value4(String value) {
        setModelGender(value);
        return this;
    }

    @Override
    public ModelRecord value5(String value) {
        setModelBorn(value);
        return this;
    }

    @Override
    public ModelRecord value6(String value) {
        setModelNationality(value);
        return this;
    }

    @Override
    public ModelRecord value7(String value) {
        setModelHeight(value);
        return this;
    }

    @Override
    public ModelRecord value8(String value) {
        setModelFigure(value);
        return this;
    }

    @Override
    public ModelRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ModelRecord
     */
    public ModelRecord() {
        super(Model.MODEL);
    }

    /**
     * Create a detached, initialised ModelRecord
     */
    public ModelRecord(Integer modelId, String modelName, String modelInstaurl, String modelGender, String modelBorn, String modelNationality, String modelHeight, String modelFigure) {
        super(Model.MODEL);

        setModelId(modelId);
        setModelName(modelName);
        setModelInstaurl(modelInstaurl);
        setModelGender(modelGender);
        setModelBorn(modelBorn);
        setModelNationality(modelNationality);
        setModelHeight(modelHeight);
        setModelFigure(modelFigure);
    }
}
