/*
 * This file is generated by jOOQ.
 */
package co.db.jooq;


import co.db.jooq.tables.Model;
import co.db.jooq.tables.records.ModelRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ModelRecord> KEY_MODEL_MODEL_HEIGHT = Internal.createUniqueKey(Model.MODEL, DSL.name("KEY_model_model_height"), new TableField[] { Model.MODEL.MODEL_HEIGHT }, true);
    public static final UniqueKey<ModelRecord> KEY_MODEL_MODEL_ID = Internal.createUniqueKey(Model.MODEL, DSL.name("KEY_model_model_id"), new TableField[] { Model.MODEL.MODEL_ID }, true);
    public static final UniqueKey<ModelRecord> KEY_MODEL_MODEL_INSTAURL = Internal.createUniqueKey(Model.MODEL, DSL.name("KEY_model_model_instaURL"), new TableField[] { Model.MODEL.MODEL_INSTAURL }, true);
    public static final UniqueKey<ModelRecord> KEY_MODEL_PRIMARY = Internal.createUniqueKey(Model.MODEL, DSL.name("KEY_model_PRIMARY"), new TableField[] { Model.MODEL.MODEL_ID }, true);
}
