/*
 * This file is generated by jOOQ.
 */
package co.db.jooq;


import co.db.jooq.tables.Model;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>model</code>.
     */
    public static final Model MODEL = Model.MODEL;
}
